VIA_ENABLE = yes
VIAL_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
LTO_ENABLE = yes

KEY_OVERRIDE_ENABLE = no
QMK_SETTINGS = no
ENCODER_MAP_ENABLE = yes
WPM_ENABLE = yes
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
